# Generated by Django 4.2.7 on 2025-12-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='package_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
